name: Update Version

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  update-version-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update version in script
      run: |
        node -e "
        const fs = require('fs');
        const path = 'script.js';
        let script = fs.readFileSync(path, 'utf8');
        let versionMatch = script.match(/var Version = \"([^\"]+)\"/);
        if (versionMatch) {
          let currentVersion = versionMatch[1];
          let [major, minor, patch] = currentVersion.split('.').map(Number);
          patch += 1; // Increment the patch version
          let newVersion = \`\${major}.\${minor}.\${patch}\`;
          script = script.replace(currentVersion, newVersion);
          fs.writeFileSync(path, script);
        }
        "

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add script.js
        git commit -m "Update version in script"
        git push
